[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "mmif-storage"
version = "0.2.0"
description = "Python interface to manage MMIF files."
readme = "README.md"
license = "Apache-2.0"
requires-python = ">=3.12"
classifiers = [
    "Development Status :: 4 - Beta",
    "Framework :: Pytest",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14"]
dependencies = [
    "pydantic==2.*",
	"mmif-python==1.4.*",
	"clams_utils==260131"]

[project.optional-dependencies]
dev = ["pytest==9.*"]

[project.scripts]
create-storage-example = "mmif_storage:create_storage_example"

[project.urls]
homepage = "https://clams.ai"
source = "https://github.com/clamsproject/mmif-storage"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["./src"]

[tool.setuptools.package-data]
mmif_storage = ["data/**/*.mmif", "data/**/*.json"]

[tool.setuptools.exclude-package-data]
mmif_storage = ["data/**/*.desc.json", "data/**/*.summ.json"]

[tool.pytest]
testpaths = ["tests"]
pythonpath = ["src"]
