[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "mmif-storage"
version = "0.1.0"
description = "Tool to manage MMIF files."
requires-python = ">=3.11"
dynamic = ["dependencies"]

[project.scripts]
start_api = "mmif_storage:start_api"
start_www = "mmif_storage:start_www"

[tool.setuptools.packages.find]
where = ["./src"]

[tool.setuptools.dynamic]
dependencies = { file = ["requirements.txt"] }
